version: '3.5'
 
services:
  apis3produto:
    build: .
    container_name: apis3produto
    hostname: apis3produto
    domainname: apis3produto.local.com
    environment:
       - "TZ=America/Sao_Paulo"
       - "API_ENV=prod"
    networks:
        apis3produtocomposer:
           aliases:
              - apis3produto.local.com
    ports:
       - 8085:8085
    env_file:
       - ./apis3produto_env.env
    restart: always

networks:
  apis3produtocomposer: 
      driver: bridge